
const textDataQuillExample = `<p><br></p><p><em style="color: rgb(7, 7, 7);">You’re back?</em><span style="color: rgb(7, 7, 7);"> 
OK, so…</span></p><p><em style="color: rgb(7, 7, 7);">Did you try the pump or push down the lid?</em></p><p><em style="color: rgb(7, 7, 7);">Did you get the lid to blow off? ;)</em></p><p><em style="color: rgb(7, 7, 7);">Did you see how pressure is connected with how the atoms move inside the container?</em></p><p><br></p><p><span style="color: rgb(7, 7, 7);">Just to answer the open questions from before:</span></p><p><strong style="color: rgb(0, 0, 0); background-color: transparent;"><em>Why does pumping increase the heat?</em></strong></p><p class="ql-indent-1"><em style="color: rgb(0, 0, 0); background-color: transparent;">Pumping (more atoms) inside a container, increases the heat because more </em> <em style="color: rgb(0, 0, 0); background-color: transparent;">atoms are moving around the same volume. So the total amount of movement goes up.</em></p><p><br></p><p><strong style="color: rgb(0, 0, 0); background-color: transparent;"><em>What actually is pressure, what is it 
represented by?</em></strong></p><p class="ql-indent-1"><em style="color: rgb(0, 0, 0); background-color: transparent;">Pressure, as within the simulation you saw, is how fast and often atoms ‘bounce’ against the walls of the container. In fact the atoms bombard the wall, pushing it away, increasing the pressure.</em></p><p><br></p><p><strong style="color: rgb(0, 0, 0); background-color: transparent;">Are pumped up basketballs hotter inside?</strong></p><p class="ql-indent-1"><em style="color: rgb(0, 0, 0); background-color: transparent;">Yep. As follows from pressure → heat observations.</em></p><p><br></p><p><strong style="background-color: rgb(255, 255, 0); color: rgb(7, 7, 7);">Turns out pressure, heat, motion and volume are all tightly interrelated. Surprise!</strong></p><p><br></p><p><span style="color: rgb(7, 7, 7);">Now with your new intuition, let’s hear Richard Feynman, one the greatest physicists of the last century, talk about his understanding of the subject.</span></p><p><br></p><p><em style="color: rgb(7, 7, 7);">The video will stop from time to time (not a bug!) to ask you to predict and guess some of the conclusions.</em></p>
Preview.js:26 reactQuill content <p>Wow, so many things that can be explained from a simple statement.</p><p><br></p><p><span style="
color: rgb(0, 0, 0); background-color: rgb(255, 255, 0);">A</span><em style="color: rgb(7, 7, 7); background-color: rgb(255, 255, 0);">
ll things are made of atoms—little particles that always move, attract each other when they are close, but repel upon being 
squeezed into one another</em><span style="color: rgb(7, 7, 7); background-color: rgb(255, 255, 0);">. </span></p>`

export {textDataQuillExample}